services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kanban-app
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: kanban-db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: kanban-nginx
    ports:
      - "${NGINX_HOST_PORT:-8000}:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    container_name: kanban-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - laravel

  node:
    image: node:20
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel
    ports:
      - "5175:5175"

volumes:
  pgdata:

networks:
  laravel:
